### PR TITLE
Hopefully this one works better.

### PR DESCRIPTION
**Pull request by subwolf**

### CODE REVIEW

**Comment by EmergentBehavior** [comment]
So three quick things:
- No `.torrent` files should be committed to the repository. Any temporary data should be in `.gitignore`.
- Tests should clean up after themselves. If you're using a temporary path, it should be created when needed and destroyed afterwards.
- Please rebase your commits into a single commit so they can be reviewed more easily together.

**Comment by subwolf** [comment]
Can't rebase with a forked repo as I didn't create my own branch first, only have master.

Otherwise, done.

**Comment by subwolf** [comment]
Passes all tests, 2.7 build failed because of Github, see https://travis-ci.org/Storj/storjtorrent/jobs/51092967 (good), https://travis-ci.org/Storj/storjtorrent/jobs/51092966 (bad)

**Comment by EmergentBehavior** [comment]
You don't need two parametrize statements for each test. You can have multiple variables used in a single `parametrize()`. Look at the PyTest docs.

Also, if you're not using `st_with_torrent()` then you don't need to check to remove those test paths. Finally, if you aren't using `pathtest` etc. in your tests then you should need to remove it.

**Pull request merged**
